### ISSUE TITLE
📝 Todo: List for Functions and Required Props for Component

### ISSUE THREAD

**Issue by ahyeon-jung** [a-honey/react-custom-calendar-heatmap#1]
## Functions
- [x] return a color based on the current value
- [x] return gradient colors based on the depth
- [x] return depth size based on maxValue and the depth
- [ ] return a total date count based on startDate and endDate

## Props
- Full color
- SVGelement
- depth
- element props: value, date, hover value
- startDate
- endDate
